name: CI

on:
  push:
  pull_request:

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    name: build • freebsd
    defaults:
      run:
        shell: freebsd {0}
    steps:
      - uses: actions/checkout@v5

      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          prepare: |
            pkg install -y cmake ninja bash capnproto git
          run: git config --global --add safe.directory ${{ github.workspace }}
          sync: 'rsync'
          copyback: false

      - name: Run CI script
        run: |
          cd ${{ github.workspace }}
          CI_CONFIG="ci/configs/freebsd.bash" bash ci/scripts/ci.sh
