name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31       # 2025-05-27, from https://github.com/cachix/install-nix-action/tags
      with:
        nix_path: nixpkgs=channel:nixos-25.05   # latest release

    - name: Configure, build, test
      run: |
        nix-shell --pure --run "ci/scripts/configure.sh"
        nix-shell --pure --run "ci/scripts/build.sh"
        nix-shell --pure --run "ci/scripts/test.sh"
